---
# tasks file for Dell-Networking.dellos-interface
 - name: "Provisioning interface configuration for dellos10"
   dellos10_config:
      src: dellos10_interface.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10")
#   notify: save config os10
   register: output


