---
# tasks file for Dell-Networking.dellos-vlt
 - name: "Provisioning VLT configuration for dellos10"
   dellos10_config:
      src: dellos10_vlt.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") 
#   notify: save config os10
   register: output


